### ISSUE TITLE
Typescript 5 and verbatimModuleSyntax

### ISSUE THREAD

**Issue by jorgebodega** [tsconfig/bases#166]
There are some packages (all that use `importsNotUsedAsValues`) that is showing a deprecation error message on typecheck. In my case, I'm using the `"@tsconfig/node18-strictest"` recommended version.

This is the specific error

```
error TS5101: Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
  Use 'verbatimModuleSyntax' instead.
```

Does someone know any way of solving this? Instead of the `ignoreDeprecations`, of course.

If someone needs help to work on this, I can try to help, but don't know where to start.

**Comment by orta** [comment]
Switch to the new server majors

**Comment by jorgebodega** [comment]
> Switch to the new semver majors which separate strict from node

What do you mean? Semver majors of what? Typescript?

**Comment by jorgebodega** [comment]
Oh great! I will close the issue, that fix the problem.

But... If there is a version with node strict that supports Typescript 5.0, why the combined package does not support it?

**Comment by szebert** [comment]
I concur with @jorgebodega , if you had 
```
// tsconfig.json
{
  "extends": ["@tsconfig/strictest/tsconfig", "@tsconfig/node18/tsconfig"]
}
```
before the change, you had 
```
{
  "compilerOptions": {
      "importsNotUsedAsValues": "error"
  }
}
```
included in the tsconfig. Now there's nothing since it's replacement, 
```
{
  "compilerOptions": {
      "verbatimModuleSyntax": true
  }
}
```
was moved to ESM (f674fa6) which isn't included in NodeJs (which typically uses CommonJS from my understanding).

This feels like a dirty fix, removing import type checking entirely for Node. Shouldn't we still care about import type checking for Node apps?
