### ISSUE TITLE
Where should the option "veratimmodulesyntax" be placed?

### ISSUE THREAD

**Issue by chshouyu** [tsconfig/bases#211]
> ### What about `@tsconfig/esm`?
> We deprecated it in favour of setting https://github.com/tsconfig/bases/pull/197 to node/bundler.

The `@tsconfig/esm` contains `verbatimModuleSyntax`, if `@tsconfig/esm` is deprecated, do I need to write it in my own tsconfig file?

<img width="355" alt="image" src="https://github.com/tsconfig/bases/assets/1304342/d8ba7a0e-a8d7-4066-a9c4-14fcb84af6d6">

Currently, only these two files contain this option.

**Comment by alecmev** [comment]
Yeah, I also don’t understand why `moduleResolution` was added to it.

**Comment by orta** [comment]
A reminder that @tsconfig/esm is deprecated.

moduleResolution is what determines how modules are looked up, and because moduleREsolution natively suports node16+ then there's no need for an esm specific runtime

WRT verbatim module syntax, that's your call - I don't necessarily think that needs to be applied to all node projects so it is something you would add if you wanted it - yes
